name: Dependabot auto-merge
on: pull_request_target

jobs:
  automerge:
    runs-on: ubuntu-latest
    # guard to ensure only bot can automerge
    if: github.actor == 'dependabot[bot]'

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.15.0
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          use-github-auto-merge: true
